# ============================================================
#  VeriFYD — ai_source_detector.py
#
#  Explicit AI-source / provenance text detector.
#
#  Purpose:
#  Catch videos whose filename, caption, sidecar metadata, title,
#  source text, or page metadata explicitly says they were made
#  with an AI generator, even if the pixels look realistic.
# ============================================================

from __future__ import annotations

import json
import os
import re
from typing import Any, Dict, Iterable, List


AI_GENERATOR_MARKERS = {
    "higgsfield.ai": "Higgsfield",
    "@higgsfield.ai": "Higgsfield",
    "higgsfield": "Higgsfield",
    "openai sora": "Sora",
    "sora": "Sora",
    "kling ai": "Kling",
    "kling": "Kling",
    "runwayml": "Runway",
    "runway ml": "Runway",
    "runway gen": "Runway",
    "runway": "Runway",
    "pika labs": "Pika",
    "pika.art": "Pika",
    "pika": "Pika",
    "google veo": "Veo",
    "veo 3": "Veo",
    "veo": "Veo",
    "seedance": "Seedance",
    "wan 2": "Wan",
    "wan ai": "Wan",
    "hailuo": "Hailuo",
    "minimax": "MiniMax",
    "luma dream machine": "Luma",
    "dream machine": "Luma",
    "midjourney": "Midjourney",
    "dall-e": "DALL-E",
    "dall·e": "DALL-E",
    "dalle": "DALL-E",
    "stable diffusion": "Stable Diffusion",
    "stability ai": "Stability AI",
    "adobe firefly": "Adobe Firefly",
    "firefly": "Adobe Firefly",
    "animatediff": "AnimateDiff",
    "cogvideo": "CogVideo",
    "videocrafter": "VideoCrafter",
}

AI_CONTEXT_PHRASES = (
    "made with",
    "made by",
    "made using",
    "generated with",
    "generated by",
    "generated using",
    "created with",
    "created by",
    "created using",
    "ai generated",
    "ai-generated",
    "synthetic video",
    "powered by",
    "using ai",
    "with ai",
)

DIRECT_DOMAIN_OR_HANDLE_MARKERS = (
    "higgsfield.ai",
    "@higgsfield.ai",
    "pika.art",
    "runwayml",
)


def _flatten_values(obj: Any, out: List[str]) -> None:
    """Recursively collect text-like values from dict/list metadata."""
    if obj is None:
        return
    if isinstance(obj, dict):
        for key, value in obj.items():
            out.append(str(key))
            _flatten_values(value, out)
    elif isinstance(obj, (list, tuple, set)):
        for value in obj:
            _flatten_values(value, out)
    elif isinstance(obj, (str, int, float, bool)):
        text = str(obj).strip()
        if text:
            out.append(text[:2000])


def _normalize_text(text: str) -> str:
    text = str(text or "").lower()
    text = text.replace("_", " ").replace("-", " ")
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def _sidecar_candidates(video_path: str) -> List[str]:
    candidates = []
    if not video_path:
        return candidates

    root, _ext = os.path.splitext(video_path)
    if root:
        candidates.append(root + ".meta.json")

    for suffix in (".mp4", ".MP4", ".mov", ".MOV", ".m4v", ".M4V", ".webm", ".WEBM"):
        if video_path.endswith(suffix):
            candidates.append(video_path[: -len(suffix)] + ".meta.json")

    seen = set()
    out = []
    for candidate in candidates:
        if candidate and candidate not in seen:
            out.append(candidate)
            seen.add(candidate)
    return out


def _read_sidecar_texts(video_path: str) -> List[str]:
    """Read any existing .meta.json sidecar and collect text values."""
    texts: List[str] = []
    for sidecar in _sidecar_candidates(video_path):
        if not os.path.exists(sidecar):
            continue
        try:
            with open(sidecar, "r", encoding="utf-8", errors="replace") as fh:
                data = json.load(fh)
            _flatten_values(data, texts)
        except Exception:
            continue
    return texts


def scan_texts_for_ai_source(texts: Iterable[str]) -> Dict[str, Any]:
    """
    Return explicit AI-source evidence from supplied text values.

    High-confidence requires either a direct AI platform domain/handle or an AI
    context phrase near a known generator/platform marker.
    """
    raw_parts = [str(t or "") for t in texts if str(t or "").strip()]
    combined_raw = " | ".join(raw_parts)
    combined = _normalize_text(combined_raw)

    empty = {
        "detected": False,
        "confidence": "none",
        "generator": "",
        "matched": "",
        "reason": "",
        "source_text": combined_raw[:1000],
        "ai_score": 0,
    }
    if not combined:
        return empty

    for marker in DIRECT_DOMAIN_OR_HANDLE_MARKERS:
        if marker in combined:
            return {
                "detected": True,
                "confidence": "high",
                "generator": AI_GENERATOR_MARKERS.get(marker, marker),
                "matched": marker,
                "reason": f"Source text explicitly references AI generator/platform: {marker}",
                "source_text": combined_raw[:1000],
                "ai_score": 97,
            }

    for marker, generator in AI_GENERATOR_MARKERS.items():
        if marker not in combined:
            continue

        marker_pos = combined.find(marker)
        context_hit = ""
        for phrase in AI_CONTEXT_PHRASES:
            phrase_pos = combined.find(phrase)
            if phrase_pos >= 0 and abs(phrase_pos - marker_pos) <= 140:
                context_hit = phrase
                break

        if context_hit:
            return {
                "detected": True,
                "confidence": "high",
                "generator": generator,
                "matched": marker,
                "reason": f"Source text says '{context_hit}' near AI generator/platform '{marker}'",
                "source_text": combined_raw[:1000],
                "ai_score": 96,
            }

        if marker in ("higgsfield", "seedance", "hailuo", "midjourney", "animatediff", "cogvideo", "videocrafter"):
            return {
                "detected": True,
                "confidence": "medium",
                "generator": generator,
                "matched": marker,
                "reason": f"Source text references likely AI generator/platform: {marker}",
                "source_text": combined_raw[:1000],
                "ai_score": 75,
            }

    return empty


def scan_video_source_for_ai(video_path: str, extra_texts: Iterable[str] | None = None) -> Dict[str, Any]:
    """
    Scan filename/path, sidecar metadata, captions, titles, and any supplied
    text for explicit AI-source evidence.
    """
    texts: List[str] = []
    if video_path:
        texts.append(os.path.basename(video_path))
        texts.append(video_path)
    texts.extend(_read_sidecar_texts(video_path))
    if extra_texts:
        texts.extend(str(t) for t in extra_texts if str(t or "").strip())
    return scan_texts_for_ai_source(texts)
